# Generated by Django 2.0.2 on 2018-02-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Datablock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31)),
                ('time', models.CharField(max_length=31)),
                ('bid', models.CharField(max_length=63)),
                ('ask', models.CharField(max_length=63)),
                ('currency1', models.ManyToManyField(to='organizer.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31)),
                ('currency', models.ManyToManyField(to='organizer.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Pairname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='pairname',
            field=models.ManyToManyField(to='organizer.Pairname'),
        ),
        migrations.AddField(
            model_name='datablock',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Exchange'),
        ),
        migrations.AddField(
            model_name='datablock',
            name='pairname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Pairname'),
        ),
        migrations.AddField(
            model_name='currency',
            name='pairname',
            field=models.ManyToManyField(to='organizer.Pairname'),
        ),
    ]
