# Generated by Django 2.0.2 on 2018-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datablock',
            old_name='currency1',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='datablock',
            name='time',
        ),
        migrations.RemoveField(
            model_name='datablock',
            name='exchange',
        ),
        migrations.AddField(
            model_name='datablock',
            name='exchange',
            field=models.ManyToManyField(to='organizer.Exchange'),
        ),
        migrations.RemoveField(
            model_name='datablock',
            name='pairname',
        ),
        migrations.AddField(
            model_name='datablock',
            name='pairname',
            field=models.ManyToManyField(to='organizer.Pairname'),
        ),
    ]
